SELECT
    s.S_SUPPKEY AS SUPPLIERKEY,
    s.S_NAME AS SUPPLIER_NAME,
    s.S_ADDRESS AS SUPPLIER_ADDRESS,
    s.S_NATIONKEY AS SUPPLIER_NATION_KEY,
    s.S_PHONE AS SUPPLIER_PHONE,
    s.S_ACCTBAL AS SUPPLIER_ACCBAL,
    s.S_COMMENT AS SUPPLIER_COMMENT,
    d.N_NAME AS SUPPLIER_NATION_NAME,
    d.N_COMMENT AS SUPPLIER_NATION_COMMENT,
    sysdate() AS SUPPLIER_DATE
FROM {{ source('tpch_sample', 'SUPPLIER') }} AS s
LEFT JOIN {{ source('tpch_sample', 'NATION') }} AS d
    ON s.S_NATIONKEY  = d.N_NATIONKEY
ORDER BY 
    s.S_SUPPKEY