SELECT
    o.O_ORDERKEY AS ORDERKEY,
    o.O_CUSTKEY AS CUSTOMER_KEY,
    o.O_ORDERSTATUS AS ORDER_STATUS,
    o.O_TOTALPRICE AS ORDER_TOTAL_PRICE,
    o.O_ORDERDATE AS ORDER_ORDER_DATE,
    o.O_ORDERPRIORITY AS ORDER_PRIORITY,
    o.O_CLERK AS ORDER_CLERK,
    o.O_SHIPPRIORITY AS ORDER_SHIP_PRIORITY,
    o.O_COMMENT AS ORDER_COMMENT,
    sysdate() AS ORDER_DATE
FROM {{ source('tpch_sample', 'ORDERS') }} AS o
ORDER BY 
    o.O_ORDERKEY