SELECT
    p.P_PARTKEY AS PARTKEY,
    p.P_NAME AS PART_NAME,
    p.P_MFGR AS PART_MFGR,
    p.P_BRAND AS PART_BRAND,
    p.P_TYPE AS PART_TYPE,
    p.P_SIZE AS PART_SIZE,
    p.P_CONTAINER AS PART_CONTAINER,
    p.P_RETAILPRICE AS PART_RETAIL_PRICE,
    p.P_COMMENT AS PART_COMMENT,
    sysdate() AS PART_DATE
FROM {{ source('tpch_sample', 'PART') }} AS p
ORDER BY 
    p.P_PARTKEY