version: 2

sources:
  - name: tpch_sample
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
    tables:
      - name: CUSTOMER
      - name: SUPPLIER
      - name: NATION
      - name: REGION
      - name: PART
      - name: ORDERS